SELECT * FROM BOARD;
SELECT * FROM USER_TABLES;
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME IN ('BOARD');
SELECT * FROM USER_CONSTRAINTS;


CREATE TABLE board (
	num number(5) PRIMARY KEY,
	pass varchar2(30),
	name varchar2(30),
	email varchar2(30),
	title varchar2(50),
	content varchar2(1000),
	readcount NUMBER(4) DEFAULT 0,
	writeDate DATE DEFAULT sysdate
);


DROP SEQUENCE BOARD_SEQ;

CREATE SEQUENCE BOARD_SEQ
	START WITH 1
	INCREMENT BY 1;
	
CREATE OR REPLACE TRIGGER TRI_BOARD_NUM_AUTOSEQ
BEFORE INSERT ON BOARD
FOR EACH ROW
BEGIN
	IF Inserting AND :NEW.NUM IS NULL THEN
		SELECT BOARD_SEQ.NEXTVAL INTO :NEW.NUM FROM DUAL;
	END IF;
END;


